package com.rafaelfelipeac.replyradar.core.strings

interface Strings {
    val appName: String

    val genericErrorMessage: String

    val replyListActivityLog: String
    val replyListTabOnTheRadar: String
    val replyListTabResolved: String
    val replyListTabArchived: String
    val replyListPlaceholderOnTheRadar: String
    val replyListGetRepliesError: String
    val replyListPlaceholderResolved: String
    val replyListPlaceholderArchived: String
    val replyListBottomSheetName: String
    val replyListBottomSheetSubject: String
    val replyListBottomSheetAdd: String
    val replyListBottomSheetSave: String
    val replyListBottomSheetResolve: String
    val replyListBottomSheetReopen: String
    val replyListBottomSheetArchive: String
    val replyListBottomSheetUnarchive: String
    val replyListBottomSheetDelete: String
    val replyListItemResolve: String
    val replyListItemCreatedAt: String
    val replyListItemUpdatedAt: String
    val replyListItemResolvedAt: String
    val replyListItemArchivedAt: String
    val replyListFabContentDescription: String
    val replyListDeleteDialogTitle: String
    val replyListDeleteDialogDescription: String
    val replyListDeleteDialogConfirm: String
    val replyListDeleteDialogDismiss: String
    val replyListSnackbarArchived: String
    val replyListSnackbarRemoved: String
    val replyListSnackbarReopened: String
    val replyListSnackbarResolved: String
    val replyListSnackbarUnarchived: String
    val replyListReminder: String
    val replyListReminderSet: String
    val replyListReminderToday: String
    val replyListReminderTomorrow: String
    val replyListReminderTimeIconContentDescription: String
    val replyListReminderDateIconContentDescription: String
    val replyListReminderCloseIconContentDescription: String
    val replyListReminderInvalidDateTime: String
    val replyListReminderTimePickerTitle: String
    val replyListReminderTimePickerConfirmButton: String
    val replyListReminderTimePickerDismissButton: String
    val replyListReminderDatePickerConfirmButton: String
    val replyListReminderDatePickerDismissButton: String

    val settingsTitle: String
    val settingsBackButton: String
    val settingsTheme: String
    val settingsThemeLight: String
    val settingsThemeDark: String
    val settingsThemeSystem: String
    val settingsLanguage: String
    val settingsLanguageEnglish: String
    val settingsLanguagePortuguese: String
    val settingsLanguageSystem: String
    val settingsFeedbackTitle: String
    val settingsFeedbackDescription: String
    val settingsFeedbackEmailSubject: String
    val settingsFeedbackEmailBody: String
    val settingsRateTitle: String
    val settingsRateDescription: String
    val settingsAppVersion: String

    val activityLogTitle: String
    val activityLogBackButton: String
    val activityLogItemContentDescription: String
    val activityLogPlaceholder: String
    val activityLogGetActivityLogsError: String
    val activityLogMessageFormat: String
    val activityLogMessageItem: String
    val activityLogMessageItemRemoved: String
    val activityLogUserActionArchiveVerb: String
    val activityLogUserActionCreateVerb: String
    val activityLogUserActionDeleteVerb: String
    val activityLogUserActionEditVerb: String
    val activityLogUserActionReopenVerb: String
    val activityLogUserActionResolveVerb: String
    val activityLogUserActionUnarchiveVerb: String
    val activityLogUserActionOpenVerb: String
    val activityLogUserActionScheduledVerb: String
    val activityLogUserActionOpenedNotificationVerb: String
    val activityLogUserActionTheme: String
    val activityLogUserActionLanguage: String
    val activityLogUserActionFeedback: String
    val activityLogUserActionRate: String

    val notificationPermissionDialogTitle: String
    val notificationPermissionDialogDescription: String
    val notificationPermissionDialogConfirmButton: String
    val notificationPermissionDialogDismissButton: String
    val notificationTitle: String
    val notificationContent: String
    val notificationContentWithoutSubject: String
}
