package com.rafaelfelipeac.replyradar.core.common.strings

object StringsPt : Strings {
    override val appName = "Reply Radar"
    override val genericErrorMessage = "Ocorreu um erro inesperado."

    override val replyListActivityLog = "Atividades"
    override val replyListTabOnTheRadar = "No Radar"
    override val replyListTabResolved = "Resolvidos"
    override val replyListTabArchived = "Arquivados"
    override val replyListPlaceholderOnTheRadar =
        "Nada no radar por enquanto!\nQue tal adicionar algo?"
    override val replyListGetRepliesError =
        "Não foi possível carregar suas mensagens. Tente novamente."
    override val replyListPlaceholderResolved =
        "Nenhuma resposta resolvida ainda.\nHora de resolver alguma coisa?"
    override val replyListPlaceholderArchived = "O arquivo está vazio!\nHora de limpar seu radar?"
    override val replyListBottomSheetName = "Nome"
    override val replyListBottomSheetSubject = "Assunto"
    override val replyListBottomSheetAdd = "Adicionar"
    override val replyListBottomSheetSave = "Salvar"
    override val replyListBottomSheetResolve = "Resolver"
    override val replyListBottomSheetReopen = "Reabrir"
    override val replyListBottomSheetArchive = "Arquivar"
    override val replyListBottomSheetUnarchive = "Desarquivar"
    override val replyListBottomSheetDelete = "Excluir"
    override val replyListItemResolve = "Resolver"
    override val replyListFabContentDescription = "Adicione uma nova mensagem ao seu radar."

    override val settingsTitle = "Configurações"
    override val settingsBackButton = "Voltar"
    override val settingsTheme = "Tema"
    override val settingsThemeLight = "Claro"
    override val settingsThemeDark = "Escuro"
    override val settingsThemeSystem = "Usar padrão do sistema"
    override val settingsLanguage = "Idioma"
    override val settingsLanguageEnglish = "Inglês"
    override val settingsLanguagePortuguese = "Português"
    override val settingsLanguageSystem = "Usar padrão do sistema"
    override val settingsFeedbackTitle = "Feedback"
    override val settingsFeedbackDescription = "Nos envie um e-mail com dúvidas, sugestões ou para relatar um problema. Seu feedback ajuda a melhorar o Reply Radar!"
    override val settingsRateTitle = "Avalie o app"
    override val settingsRateDescription = "Curtiu o Reply Radar? Deixe uma avaliação na Play Store e ajude mais pessoas a descobrirem o app!"
    override val settingsAppVersion = "Reply Radar - Versão:"

    override val activityLogTitle = "Registro de atividades"
    override val activityLogBackButton = "Voltar"
    override val activityLogItemContentDescription = "Item de registro de atividades"
    override val activityLogPlaceholder =
        "Nenhuma atividade por enquanto!\nSeu radar está esperando por ação."
    override val activityLogGetActivityLogsError =
        "Não foi possível carregar seu histórico de atividades. Tente novamente."
    override val activityLogMessageFormat = "Você %1 %2"
    override val activityLogMessageItem = "o item \"%1\"."
    override val activityLogMessageItemRemoved = "um item que já não existe mais."
    override val activityLogUserActionArchiveVerb = "arquivou"
    override val activityLogUserActionCreateVerb = "criou"
    override val activityLogUserActionDeleteVerb = "removeu"
    override val activityLogUserActionEditVerb = "editou"
    override val activityLogUserActionReopenVerb = "reabriu"
    override val activityLogUserActionResolveVerb = "resolveu"
    override val activityLogUserActionUnarchiveVerb = "desarquivou"
    override val activityLogUserActionTheme = "Você mudou o tema do app."
    override val activityLogUserActionLanguage = "Você mudou o idioma do app."
}
