style:
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - 'Test'
  MaxLineLength:
    active: true
    maxLineLength: 150
  WildcardImport:
    active: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
  ReturnCount:
    active: true
    max: 5

naming:
  FunctionNaming:
    active: true
    functionPattern: '^([a-z][a-zA-Z0-9]*)|(`.*`)$'
    ignoreAnnotated:
      - 'Composable'

  VariableNaming:
    active: true
    variablePattern: '^(_)?[a-z][A-Za-z0-9]*$'

  TopLevelPropertyNaming:
    active: false


complexity:
  LongMethod:
    active: true
    threshold: 150
  LargeClass:
    active: true
    threshold: 600
  CyclomaticComplexMethod:
    active: true
    threshold: 20
  LongParameterList:
    active: true
    constructorThreshold: 15
    functionThreshold: 15
  TooManyFunctions:
    active: true
    thresholdInClasses: 30
    thresholdInFiles: 30

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
