name: "🚀 Release"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode release.keystore from secret
        run: echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > release.keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

      - name: Configure release signing properties
        run: |
          mkdir -p ~/.gradle
          echo "RELEASE_KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties

      - name: Run tests
        run: ./gradlew test

      - name: Check versionCode/versionName bumped
        run: |
          VERSION_NAME=$(grep versionName composeApp/build.gradle.kts | grep -oP '"\K[^"]+')
          VERSION_CODE=$(grep versionCode composeApp/build.gradle.kts | grep -oP '[0-9]+')
          echo "versionName=$VERSION_NAME"
          echo "versionCode=$VERSION_CODE"
          [[ $VERSION_NAME != "" && $VERSION_CODE != "" ]]

      - name: Build APK
        run: ./gradlew :composeApp:assembleRelease

      - name: Build AAB
        run: ./gradlew :composeApp:bundleRelease

      - name: Rename release artifacts
        run: |
          VERSION=${{ github.ref_name }}
          mv composeApp/build/outputs/apk/release/composeApp-release.apk composeApp/build/outputs/apk/release/replyradar-$VERSION.apk
          mv composeApp/build/outputs/bundle/release/composeApp-release.aab composeApp/build/outputs/bundle/release/replyradar-$VERSION.aab

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            composeApp/build/outputs/apk/release/replyradar-*.apk
            composeApp/build/outputs/bundle/release/replyradar-*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
